config/routes.rb
Rails.application.routes.draw do
  get 'snipets/starred' => 'snipets#my_starred_snipets', :as => :my_starred_snipets
  resources :snipets
  devise_for :users

  root 'snipets#index'

  get 'users/:id/snipets' => 'snipets#my_snipets', :as => :my_snipets
  put 'snipets/:id/star' => 'snipets#star', :as => :star
  get 'snipets/:id/star_info' => 'snipets#star_info', :as => :star_info

  post 'save_output' => 'snipets#save_execution_output'

  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/snipet.rb
class Snipet < ActiveRecord::Base
  belongs_to :user
  has_many :stars
  has_many :starring_users, :class_name => "User", :through => :stars
  validates :title, presence: true, length: { minimum: 2 }
  validates :content, presence: true, length: { minimum: 2 }

  def toggle_star(user)
    star = stars.find_by_user_id(user.id)
    if star
      star.destroy
      return false
    else
      stars.create(:user_id => user.id)
      return true
    end
  end
end

app/models/star.rb
class Star < ActiveRecord::Base
  belongs_to :user
  belongs_to :snipet
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :snipets
  has_many :stars
  has_many :starred_snipets, :through => :stars, :source => :snipet
  validates_presence_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Add custom parameter "username" to devise's User
  # Hack found here: http://www.peoplecancode.com/tutorials/adding-custom-fields-to-devise

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password)}
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
    end

end

app/controllers/comments_controller.rb
class SnipetsController < ApplicationController

end

app/controllers/snipets_controller.rb
class SnipetsController < ApplicationController
  before_action :set_snipet, only: [:show, :edit, :update, :destroy, :star, :star_info]
  before_action :authenticate_user!, except: [:index, :show, :star_info]

  # GET /snipets
  def index
    @snipets = Snipet.all
  end

  def my_snipets
    @snipets = Snipet.where(user_id: current_user.id)
    render "index"
  end

  def my_starred_snipets
    @snipets = current_user.starred_snipets
    @header = "Starred snippets"
    render "index"
  end

  # GET /snipets/1
  def show
  end

  # GET /snipets/new
  def new
    @snipet = Snipet.new
  end

  def save_execution_output
    snipet = Snipet.find params[:id]
    snipet.execution_output = params[:output]
    snipet.save
    flash[:success] = "Snipet successfully saved."
    @snipets = Snipet.all
  end

  # GET /snipets/1/edit
  def edit
  end

  # POST /snipets
  def create
    @snipet = Snipet.new(snipet_params)
    @snipet.user_id = current_user.id
    @snipet.username = current_user.username
    if @snipet.save
      redirect_to({action: "my_snipets", id: current_user.id}, notice: 'Snipet was successfully created.')
    else
      render :new 
    end
  end

  # PATCH/PUT /snipets/1
  def update
    if @snipet.update(snipet_params)
      redirect_to @snipet, notice: 'Snipet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /snipets/1
  def destroy
    @snipet.destroy
    redirect_to snipets_url, notice: 'Snipet was successfully destroyed.' 
  end

  def star
    star_toggle = @snipet.toggle_star(current_user)
    star_count = @snipet.stars.count
    starred = {"starred" => star_toggle, "star_count" => star_count}
    render json: starred
  end

  def star_info
    is_starred = false
    auth_user = false
    if current_user
        auth_user = true
        is_starred = !@snipet.stars.where(:user_id => current_user.id).empty?
    end
    star_count = @snipet.stars.count
    starred = {"starred" => is_starred, "star_count" => star_count, "auth_user" => auth_user}
    render json: starred
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snipet
      @snipet = Snipet.find_by_id(params[:id])
      unless @snipet
        flash[:alert] = "No snippet found with the id " + params[:id]
        redirect_to :action => :index
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snipet_params
      params.require(:snipet).permit(:title, :content, :execution_output)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snipets_helper.rb
module SnipetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shellhub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="shellhub">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ShellHub</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to('All snipets', snipets_url) %> </li>
            <% if user_signed_in? %>
                <li>
                    <%= link_to('New snipet', new_snipet_url) %>
                </li>
                <li>
                    <%= link_to('My snipets', my_snipets_url(current_user.id)) %>
                </li>
                <li>
                    <%= link_to('My starred snipets', my_starred_snipets_url) %>
                </li>

                <li>
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
                </li>
          <% else %>
            <li>
                <%= link_to('Login', new_user_session_path)  %>  
            </li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
    </div>
</div>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/snipets/_form.html.erb
<div class="col-md-4 col-md-offset-4">
<%= form_for @snipet, :html => { :class => "form-horizontal snipet" } do |f| %>

    <% if @snipet.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@snipet.errors.count, "error") %> prohibited this snipet from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @snipet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%#= f.text_field :user_id, :class => 'form-control' %>
      <%= user_signed_in? ? current_user.username : ""%>
    </div>
    <%= error_span(@snipet[:user_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@snipet[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :content, :class => 'form-control' %>
    </div>
    <%= error_span(@snipet[:content]) %>
  </div>
  <% if action_name != "new" && action_name != "edit" %>
      <div class="control-group">
        <%= f.label :execution_output, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :execution_output, :class => 'form-control' %>
        </div>
        <%= error_span(@snipet[:execution_output]) %>
      </div>
  <% end %>
  <div class="row">&nbsp;</div>

  <%= f.submit nil, :class => 'btn btn-primary', :id => 'submit_snipet' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            snipets_path, :class => 'btn btn-default' %>

<% end %>
</div>

app/views/snipets/edit.html.erb
<%- model_class = Snipet -%>
<div class="page-header col-md-4 col-md-offset-4">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/snipets/index.html.erb
<%- model_class = Snipet -%>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="page-header">
            <h1><%= @header || "Snipets" %></h1>
        </div>
    </div>
</div>
<div class="row">
    <% @snipets.each do |snipet| %>
        <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><%= snipet.title %></h3>
            </div>
            <div class="panel-body">
                <div>
                    <b>author:</b> <%= snipet.username %>
                </div>
                <div>
                    <b>added:</b> <%= snipet.created_at.strftime("%F") %>
                </div>

                <div>
                    <b>command:</b> <%= snipet.content %>
                </div>
            </div>
            <div class="panel-footer">
                  <%= link_to "show", snipet_path(snipet), class: "btn btn-primary" %>
                  <%= link_to  "edit", edit_snipet_path(snipet), class: "btn btn-primary" if  user_signed_in? && current_user.id == snipet.user_id %>
                  <%= link_to  "delete", snipet_path(snipet), method: "delete", data: {confirm: "Are you sure ?"}, class: "btn btn-danger" if  user_signed_in? && current_user.id == snipet.user_id %>
            </div>
        </div>
    </div>
<% end %>
</div>

app/views/snipets/new.html.erb
<%- model_class = Snipet -%>
<div class="page-header col-md-4 col-md-offset-4">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/snipets/show.html.erb
<%- model_class = Snipet -%>
<div class="page-header col-md-4 col-md-offset-4">
    <h1>
        <%=t '.title', :default => model_class.model_name.human.titleize %>
        <span ng-controller="StarController" ng-cloak>
            <span id="star_counter" class="small pull-right">{{starCount}}</span>
            <span><a id="star_icon" href="#" ng-click="giveSnippetAStar(<%= @snipet.id %>)" class="glyphicon pull-right" ng-disabled="!authUser"
                    ng-class="{'glyphicon-star' : starred, 'glyphicon-star-empty' : !starred}" aria-hidden="true"></a>
            </span>
        </span>
    </h1>
</div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <dl class="dl-horizontal">
                <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
                <dd><%= @snipet.title %></dd>
                <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
                <dd><%= @snipet.content %></dd>
                <dt><strong>author:</strong></dt>
                <dd><%= @author ? @author.username : "" %></dd>
                <dt><strong><%= model_class.human_attribute_name(:execution_output) %>:</strong></dt>
                <dd><div class="panel panel-default terminal">
                    <div class="panel-body" id="execution-output">
                        <%= raw @snipet.execution_output %>
                    </div>
                </div>
                </dd>
            </dl>
            <%= link_to t('.back', :default => t("helpers.links.back")),
                snipets_path, :class => 'btn btn-default'  %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_snipet_path(@snipet), :class => 'btn btn-default' if  user_signed_in? && current_user.id == @snipet.user_id%>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                snipet_path(@snipet),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' if  user_signed_in? && current_user.id == @snipet.user_id%>
            <%#<% if  user_signed_in? && current_user.id == @snipet.user_id %>    <button class="btn btn-success" id="launchSnipet">execute command</button><%# end %>
<div ng-controller="CommentController">
    </div>
</div>
</div>
<script>
$(document).ready(function() {
        $('#launchSnipet').click(function() {
            var instruction = "<%= @snipet.content %>" ;
            var snipetId = <%= @snipet.id %> ;
            $.post("https://shellhub-api.herokuapp.com/run",JSON.stringify({command : instruction})).
            done(function(data) {
                var str="";
                data.result.forEach(function(line){
                    str = str + line + "<br/>";
                    });
                $("#execution-output").html(str);
                $.post("/save_output", {id: snipetId, output: str});
                });
            });

        });
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>